Need to use at least Python 3.11 for Cirq 1.6+
The Python `typing` package changed in at least one respect between
Python 3.10 and 3.11: in 3.10, it did not have the symbol `Self`). Cirq
1.6+ assumes that the `Self` is defined by importing `typing`, and fails
in Python 3.10. This leads to the error seen in the CI runs

https://github.com/tensorflow/quantum/actions/runs/17288698138/job/49070859286

```
ImportError: cannot import name 'Self' from 'typing'
```